# version: "3.9"

services:
  reveal:
    image: nginx:alpine
    container_name: revealjs-web
    ports:
      - "18000:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
